version: 2.1
orbs:
  doctl: digitalocean/cli@0.1.1
  node: circleci/node@5.1.0

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm test
  deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - doctl/install
      - doctl/initialize:
          digitalocean-access-token: dgo_access_token
      - run:
          name: Install Serverless
          command: doctl serverless install
      - run:
          name: Deploy to DigitalOcean
          command: npm run deploy
workflows:
  test_functions:
    jobs:
      - test
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
