version: 2.1
orbs:
  doctl: digitalocean/cli@0.1.1
  node: circleci/node@5.1.0

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm test
workflows:
  install_and_configure_cli:
    jobs:
      - doctl/install_and_initialize_cli:
          digitalocean-access-token: ${dgo_access_token}
  test_functions:
    jobs:
      - test
  deploy:
    jobs:
      - node/run:
          npm-run: deploy
