version: 2.1
orbs:
  doctl: digitalocean/cli@0.1.1
  node: circleci/node@5.1.0

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm test
