version: 2.1

orbs:
  doctl: digitalocean/cli@1.0.0
  node: circleci/node@18.13

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm test
